return {
	{ "tiagovla/scope.nvim" },
	{ "folke/lsp-colors.nvim" },
	--'nhooyr/neoman.vim'
	--'wfxr/minimap.nvim',
	{ "mrjones2014/legendary.nvim" },
	-- 'nvimdev/lspsaga.nvim',
	-- 'rebelot/heirline.nvim',
	{ "mbbill/undotree" },
	-- 'vim-tmux-navigator',
	{ "kylechui/nvim-surround" },
	{ "onsails/lspkind.nvim" },
	-- 'andersevenrud/cmp-tmux',
	-- 'nvim-tree/nvim-tree.lua',
	{ "kevinhwang91/rnvimr" },
	-- 'stevearc/resession.nvim',
	{ "kevinhwang91/nvim-ufo" },
	{ "Vonr/align.nvim" },
	--"Yggdroot/indentLine",
	{ "NMAC427/guess-indent.nvim" },
	{ "windwp/nvim-autopairs" },
	--'Iron-E/nvim-libmodal',
	--'Iron-E/nvim-bufmode',
	--'Iron-E/nvim-tabmode',
	{ "chrisbra/NrrwRgn" },
	{ "kevinhwang91/promise-async" },
	--'max397574/better-escape.nvim',
	--'SmiteshP/nvim-navbuddy'
	{ "Vigemus/iron.nvim" },
	{ "akinsho/toggleterm.nvim" },
	{ "folke/flash.nvim" },
	--'s1n7ax/nvim-window-picker',
	--'mrjones2014/smart-splits.nvim'
	{ "WhoIsSethDaniel/toggle-lsp-diagnostics.nvim" },
    { "christoomey/vim-system-copy" },
    { "ojroques/vim-oscyank" },
    { "smoka7/multicursors.nvim" },
    { "GCBallesteros/NotebookNavigator.nvim" },
    { "GCBallesteros/jupytext.nvim" },
    { "benlubas/molten-nvim" },
    { "3rd/image.nvim"}
}
