return {
  "tiagovla/scope.nvim",
  "folke/lsp-colors.nvim",
  --'nhooyr/neoman.vim'
  --'wfxr/minimap.nvim',
  -- 'mrjones2014/legendary.nvim',
  -- 'nvimdev/lspsaga.nvim',
  -- 'rebelot/heirline.nvim',
  -- 'mbbill/undotree',
  -- 'vim-tmux-navigator',
  "kylechui/nvim-surround",
  "onsails/lspkind.nvim",
  -- 'andersevenrud/cmp-tmux',
  -- 'numToStr/Comment.nvim',
  -- 'nvim-tree/nvim-tree.lua',
  -- 'kevinhwang91/rnvimr',
  -- 'stevearc/resession.nvim',
  "kevinhwang91/nvim-ufo",
  "Vonr/align.nvim",
  --"Yggdroot/indentLine",
  "NMAC427/guess-indent.nvim",
  "windwp/nvim-autopairs",
  --'Iron-E/nvim-libmodal',
  --'Iron-E/nvim-bufmode',
  --'Iron-E/nvim-tabmode',
  "chrisbra/NrrwRgn",
  "kevinhwang91/promise-async",
  --'max397574/better-escape.nvim',
  "phaazon/hop.nvim",
  --'SmiteshP/nvim-navbuddy'
  "Vigemus/iron.nvim",
  "akinsho/toggleterm.nvim",
  "folke/flash.nvim",
  -- "hrsh7th/cmp-vsnip",
  -- "hrsh7th/vim-vsnip",
  --'s1n7ax/nvim-window-picker',
  --'mrjones2014/smart-splits.nvim'
}
