name: CI

on:
  pull_request:

jobs:
  linux-64:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main

      - name: Set up working directories
        run: |
          mkdir -p ${HOME}/.local/share/chezmoi
          cp -r * ${HOME}/.local/share/chezmoi

      - name: Set up chezmoi
        run: |
          cd ${HOME}
          sh -c "$(curl -fsLS get.chezmoi.io)"

      - name: Test chezmoi
        run: |
          export FULL_INSTALL=1
          export PATH="${HOME}/bin:${PATH}"
          chezmoi apply
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  osx-64:
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Free Disk Space (macOS)
        run: |
          rm -rf ${HOME}/Library/Developer/CoreSimulator

      - name: Set up working directories
        run: |
          mkdir -p ${HOME}/.local/share/chezmoi
          cp -r * ${HOME}/.local/share/chezmoi

      - name: Set up chezmoi
        run: |
          cd ${HOME}
          sh -c "$(curl -fsLS get.chezmoi.io)"

      - name: Test chezmoi
        run: |
          export PATH="${HOME}/bin:${PATH}"
          chezmoi apply
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  osx-arm64:
    runs-on: macos-14
    strategy:
      fail-fast: false

    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Free Disk Space (macOS)
        run: |
          rm -rf ${HOME}/Library/Developer/CoreSimulator

      - name: Set up working directories
        run: |
          mkdir -p ${HOME}/.local/share/chezmoi
          cp -r * ${HOME}/.local/share/chezmoi

      - name: Set up chezmoi
        run: |
          cd ${HOME}
          sh -c "$(curl -fsLS get.chezmoi.io)"

      - name: Test chezmoi
        run: |
          export PATH="${HOME}/bin:${PATH}"
          chezmoi apply
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
